### ISSUE TITLE
Invoke API - Test API - KeyError: 'refresh_token'

### ISSUE THREAD

**Issue by jiatern** [QuiltMeow/KeepAliveE5#6]
```
Run bash routine.sh
應用資訊已解密
Traceback (most recent call last):
  File "/home/runner/work/KeepAliveE5/KeepAliveE5/task.py", line 103, in <module>
    multip_accounts_task(invoke_api)
  File "/home/runner/work/KeepAliveE5/KeepAliveE5/util.py", line 24, in multip_accounts_task
    print(f'{future.result()}')
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/work/KeepAliveE5/KeepAliveE5/task.py", line 34, in invoke_api
    tokens = get_access_token(app)
  File "/home/runner/work/KeepAliveE5/KeepAliveE5/task.py", line 24, in get_access_token
    'refresh_token': app['refresh_token'],
KeyError: 'refresh_token'
應用資訊已加密
```
Invoke API workflow 里面的Test API步骤有 `KeyError: 'refresh_token'` 的问题，要怎样解决?

**Comment by KawakazeNotFound** [comment]
重新运行Register app

**Comment by iStarCc** [comment]
同样的问题，最近出现的
